export ES_CLOUD_ID="<Elastic Cloud ID>"
export ES_USERNAME="<Elasticsearch user name>"
export ES_PASSWORD="<Elasticsearch Password>"
export FLAN_T5_ENDPOINT="<SageMaker Endpoint Name>"
export AWS_REGION="<Replace the value of the AWS Region by referring the Output Properties section>"
