export ES_CLOUD_ID="<Elastic Cloud ID>"
export ES_USERNAME="<Elasticsearch user name>"
export ES_PASSWORD="<Elasticsearch Password>"
export FLAN_T5_ENDPOINT="<SageMaker Endpoint Name>"
export AWS_REGION="us-west-1"
